### ISSUE TITLE
Add downloading of firebase config files to CI workflow

### ISSUE THREAD

**Issue by nickmeinhold** [adventuresin/chat_app#38]
I thought one way to do this would be to keep the config files in a GCS bucket and download with gsutil.

[gsutil](https://cloud.google.com/storage/docs/gsutil) is included in the gscloud SDK, as described [here](https://github.com/GoogleCloudPlatform/github-actions/issues/13) 

We can use the gsutil [cp](https://cloud.google.com/storage/docs/gsutil/commands/cp) command to download the files we need, which are: 
- GoogleService-Info.plist 
- google-services.json 

These are now stored in a [Credentials Bucket](https://console.cloud.google.com/storage/browser/adventures-in-credentials?project=adventures-in)

In order to authenticate gsutil, I created a service account and downloaded a private key. 

The service account is `ci-service-account@adventures-in.iam.gserviceaccount.com`

We need to add the service account details as secrets, see: [Creating and storing encrypted secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)

I created secrets: 
- GCS_EMAIL 
- GCS_KEY 

Note: GCS_KEY is the downloaded key file encoded in base64, as per [this](https://github.com/GoogleCloudPlatform/github-actions/blob/master/setup-gcloud/README.md).

Now (hopefully) we just need something like this added to the existing workflow:
```
- name: Authenticate gsutil
  uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  with:
    version: '270.0.0'
    service_account_email: ${{ secrets.GCS_EMAIL }}
    service_account_key: ${{ secrets.GCS_KEY }}
- name: Download config files
  run: gsutil cp gs://adventures-in-credentials/GoogleService-Info.plist ./ios/Runner/GoogleService-Info.plist
  run: gsutil cp gs://adventures-in-credentials/google-services.json ./android/app/google-services.json
```
